### ISSUE TITLE
Requesting a mupen64plus core

### ISSUE THREAD

**Issue by lukebranan** [andymcca/libretro-cores-leap#1]
I saw that you had compiled a psx core, which made me wonder if it was possible to run N64 games on the Leapster. Could you compile a mupen64plus core? If you don't want to, could you show me how I could go about doing that myself? Thanks!

**Comment by andymcca** [comment]
Hiya, there are two reasons why I haven't - one is the button/joypad config (no analog stick or C-buttons on the Leapster) and the other is I think it would struggle to give decent performance even on Retroleap OC.  I don't mind giving it a try though.  If you want to do this, the best way would be to build Retroleap yourself (instructions on that repo) and add mupen64plus as a buildroot package to the menuconfig.  That's how I've built these other cores, because then you ensure you have the correct toolchain etc in place for cross-compilation.

**Comment by andymcca** [comment]
Actually - the third most important reason!!  Retroleap currently uses a software renderer via SDL.  Both mupen64plus and parallel64 cores require OpenGL.  There is a software renderer (angrylion) but this requires a fast, modern CPU and the Leapster/GS just aren't that!  So I think you're going to be out of luck I'm afraid.

**Comment by lukebranan** [comment]
Oh, okay. I just wanted to know whether it was possible. Thanks anyway!
