### ISSUE TITLE
requesting lr-gw

### ISSUE THREAD

**Issue by lukebranan** [andymcca/libretro-cores-leap#2]
Hi! I don't mean to bother you, but I just discovered a really fun Game & Watch game called "Roller Coaster" and wanted to play it on my Leapster GS, but it wasn't in any of the Game & Watch Galleries. Could you add lr-gw? (I would try to do it myself, but I don't know how to add buildroot packages. Maybe you could make a new video about adding cores?)

**Comment by andymcca** [comment]
Hi there,  adding cores when building Retroleap is reasonably straightforward, you just need to run 'make menuconfig' and then go to Target Packages -> Games -> Emulators -> RetroArch -> Cores and select the ones you want.  The caveats are that the Buildroot package files in Retroleap can be somewhat outdated and pointing at fairly stale Github branches, They also sometimes won't build due to compilation errors meaning you have to dive in to the code to try and fix them - hence why I created this repo for pre-compiled cores!

I'll have a look at adding lr-gw.  I've recently been working on Retroleap/RetroArch for the Leapster Explorer so will finish up compiling cores on there first and upload them here, then switch back to a GS build to look at lr-gw amongst other things.

**Comment by andymcca** [comment]
@lukebranan I've just added this core to the repo, but not tested it yet as still working on some other bits.  Let me know if it works ok?  Thanks!

**Comment by andymcca** [comment]
OK have had a play - there are no core options to set but you can zoom in etc using the buttons.  

These aren't set up very well though, so would be worth doing a core remap in the RetroArch options to better mirror the expected functionality

**Comment by lukebranan** [comment]
I tried 5 or so of my game and watch games and they all worked. Thanks so much for the help! (I have almost no idea what I'm doing.)
